export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_IN_PROGRESS ="LOGIN_IN_PROGRESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SET_CURRENT_USER= "SET_CURRENT_USER";
export const SIGNUP_ERROR = "SIGNUP_ERROR";


export const FETCH_MOBILES_ERROR ="FETCH_MOBILES_ERROR";
export const FETCH_MOBILES_SUCCESS ="FETCH_MOBILES_SUCCESS";
export const FETCH_MOBILES_INPROGRESS ="FETCH_MOBILES_INPROGRESS";